function TYPE()
{
    this.CNTT       = 0;              // Công nghệ thông tin
    this.KT         = 1;              // Kinh tế và phát triển nông thôn
    this.CN         = 2;              // Chăn nuôi
    this.CNTP       = 3;              // Công nghệ thực phẩm
    this.CD         = 4;                // Cơ điện
    this.CNSH       = 5;              // Công nghệ sinh học
    this.GDQP       = 6;              // Giáo dục quốc phòng
    this.KTQT       = 7;              // Kế toán quản trị
    this.LLCT       = 8;              // Lý luận chính trị
    this.MT         = 9;                // Môi trường 
    this.NH         = 10;                // Nông học
    this.QLDD       = 11;              // Quản lý đất đai
    this.SP         = 12;                // Sư phạm
    this.TY         = 13;                // Thú y
    this.TS         = 14;                // Thủy sản

    this.MYLOCATION = 15;               // Chỉ vị trí của người dùng
    this.SELECTOR   = 16;               // Chỉ icon khi click chuột trên bản đồ
}

function MEDIAENUM(){
    this.IMAGE = 0;
    this.VIDEO = 1;
}

var MEDIATYPE = new MEDIAENUM();
var ICONTYPE = new TYPE();      // Định nghĩa enum TYPE dưới dạng biến để sử dụng ở dạng iconType.CNTT thay vì (new TYPE()).CNTT

var markersJson = [{'position': {'lat': 21.040242, 'lng': 105.870352},
					'type': ICONTYPE.CNTT,
					'name': "Đoàn 01",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},// Đoạn json này chỉ để demo về nguyên tắc không được show đoạn này ra khi chạy thật, cần thiết kế 1 đoạn ajax để lấy đoạn json này
					
					{'position': {'lat': 21.053699, 'lng': 105.895586},
					'type': ICONTYPE.KT,
					'name': "Đoàn 02",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.032071, 'lng': 105.887609},
					'type': ICONTYPE.CN,
					'name': "Đoàn 03",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.105551, 'lng': 105.873013},
					'type': ICONTYPE.CNTP,
					'name': "Đoàn 04",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.045003, 'lng': 105.839367},
					'type': ICONTYPE.CD,
					'name': "Đoàn 05",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.017444, 'lng': 105.898762},
					'type': ICONTYPE.CNSH,
					'name': "Đoàn 06",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.112277, 'lng': 106.015835},
					'type': ICONTYPE.KTQT,
					'name': "Đoàn 07",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.017444, 'lng': 105.989056},
					'type': ICONTYPE.LLCT,
					'name': "Đoàn 08",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.057179, 'lng': 105.797138},
					'type': ICONTYPE.MT,
					'name': "Đoàn 09",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.056858, 'lng': 105.964680},
					'type': ICONTYPE.NH,
					'name': "Đoàn 10",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.078964, 'lng': 105.933094},
					'type': ICONTYPE.QLDD,
					'name': "Đoàn 11",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.023213, 'lng': 105.930691},
					'type': ICONTYPE.SP,
					'name': "Đoàn 12",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.122205, 'lng': 105.926228},
					'type': ICONTYPE.TY,
					'name': "Đoàn 13",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]},

					{'position': {'lat': 21.027379, 'lng': 105.988369},
					'type': ICONTYPE.TS,
					'name': "Đoàn 14",
					'boss': "Ngô Công Thắng",
					'faculty': "Công nghệ thông tin",
					'department': "Công nghệ phần mềm",
					'address': {'name': 'Học viện Nông Nghiệp Việt Nam',
								'specific_add': 'Số 286 Đội Cấn, Phường Cống Vị',
								'township': 'Ba Đình',
								'city': 'Hà Nội',
								'phone': '0488888888'},
				    'time': {'startDate': "01/01/2017", 'endDate': "10/01/2017"},
				    'media': [{'url':'../Contents/03_images/01_myImages/Marker_media/4.jpg', 'type':MEDIATYPE.IMAGE, 'height': 1131, 'width': 1698, 
				    			'comments': [{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 1, 'childs':null},
											{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'id': 2, 'childs':[{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null},
																																																			{'content':'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s', 'timespan':'1 tiếng trước', 'userFullName':'Ngô Công Thắng', 'userAvatar':'../Contents/03_images/01_myImages/avatar.png', 'childs':null}]}]},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/5.jpg', 'type':MEDIATYPE.IMAGE, 'height': 333, 'width': 500},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/6.jpg', 'type':MEDIATYPE.IMAGE, 'height': 419, 'width': 630},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/7.jpg', 'type':MEDIATYPE.IMAGE, 'height': 606, 'width': 848},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/8.jpg', 'type':MEDIATYPE.IMAGE, 'height': 267, 'width': 400},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/9.jpg', 'type':MEDIATYPE.IMAGE, 'height': 667, 'width': 1000},
				    		  {'url':'../Contents/03_images/01_myImages/Marker_media/video.mp4', 'type':MEDIATYPE.VIDEO, 'height': 0, 'width': 0}],
				    'id': 1,
				    'student': [{'name':'Nguyễn Văn A', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn B', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn C', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn D', 'code':'588888', 'class':'K58QLTT'},
				    			{'name':'Nguyễn Văn E', 'code':'588888', 'class':'K58QLTT'}],
				    'history': [{'date':'18/03/2017 12:00', 'position':{'lat': 21.045952, 'lng': 105.876832}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.050450, 'lng': 105.892582}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 21.032186, 'lng': 105.909748}, 'type': ICONTYPE.CNTT},
							    {'date':'18/03/2017 12:00', 'position':{'lat': 20.998535, 'lng': 105.937557}, 'type': ICONTYPE.CNTT}
					]}];